modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="radiantgems"
version="1.0.0"
displayName="Radiantgems"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="coryhubbard"

[[dependencies.radiantgems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




